=== RADAR-base/RADAR-aRMT-protocols/docs/protocol-schema-0.1.5.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://radar-base.org/armt/protocol/0.1.5",
  "type": "object",
  "title": "RADAR-base protocol for the aRMT app questionnaire delivery",
  "description": "A protocol for the RADAR-base aRMT app describes what questionnaires should be proposed to participants at what time. It controls notification times, label text and the questionnaire sources. The reference questionnaire app is described on the wiki page https://radar-base.atlassian.net/wiki/spaces/RAD/pages/463241217/Protocol+Schedule.",
  "required": [
    "version",
    "schemaVersion",
    "name",
    "protocols"
  ],
  "properties": {
    "version": {
      "allOf": [
        {
          "$ref": "#/$defs/version"
        },
        {
          "title": "Protocol version",
          "description": "Update this version whenever the aRMT app should read any changes."
        }
      ]
    },
    "schemaVersion": {
      "type": "string",
      "format": "uri-reference",
      "title": "Reference to this schema",
      "description": "The version of this schema describing the protocol structure.",
      "examples": [
        "https://radar-base.org/armt/protocol/0.1.0"
      ]
    },
    "name": {
      "type": "string",
      "title": "Protocol set name",
      "description": "The name of the set of protocols. It should match the study that the protocol is being used in.",
      "examples": [
        "RADAR MDD KCL s1"
      ]
    },
    "healthIssues": {
      "type": "array",
      "title": "Health issues",
      "description": "Study area of health issues that are covered by the questionnaire.",
      "items": {
        "type": "string",
        "examples": [
          "depression"
        ]
      }
    },
    "protocols": {
      "type": "array",
      "title": "Questionnaire protocols",
      "description": "List of questionnaire protocols in the study protocol.",
      "items": {
        "$ref": "#/$defs/protocol"
      }
    }
  },
  "$defs": {
    "protocol": {
      "type": "object",
      "title": "Questionnaire protocol",
      "description": "Single questionnaire protocol.",
      "required": [
        "name",
        "showIntroduction",
        "questionnaire",
        "startText",
        "endText",
        "warn",
        "estimatedCompletionTime",
        "protocol"
      ],
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^[A-Za-z0-9]+([ _,-]+[A-Za-z0-9]+)*$",
          "title": "Questionnaire name",
          "examples": [
            "PHQ8",
            "SAMPLE_INPUT_DEMO",
            "Tandem Walking Test"
          ],
          "description": "Name of the questionnaire. This should be either space (capitalised) or underscore separated (any case). See example above."
        },
        "showIntroduction": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "string",
              "enum": [
                "always",
                "once",
                "never"
              ]
            }
          ],
          "title": "Show an introduction",
          "description": "True or 'once' if an introduction to the questionnaire should be shown once, false or 'never' otherwise. If the introduction should always be shown, value set should be 'always'. The contents of the introduction are defined by the 'startText' property.",
          "default": false
        },
        "showInCalendar": {
          "type": "boolean",
          "title": "Whether the questionnaire should show up on the task calendar.",
          "description": "True if the questionnaire should show up on the task calendar and show task information, or false, if it should be hidden (for example, for randomised questionnaires).",
          "default": true
        },
        "isDemo": {
          "type": "boolean",
          "title": "Whether the questionnaire is only a demo",
          "description": "True if the questionnaire is only a demo, so the data for the questionnaire should not be sent to the server.",
          "default": false
        },
        "order": {
          "type": "integer",
          "title": "Order for showing tasks in the home page",
          "description": "Order for choosing tasks to prioritize in the home page when multiple tasks are pending and order for showing clinical tasks, where 0 has the highest order/priority.",
          "default": 0
        },
        "questionnaire": {
          "$ref": "#/$defs/questionnaire"
        },
        "startText": {
          "allOf": [
            {
              "$ref": "#/$defs/multiLanguageText"
            },
            {
              "title": "Start text",
              "description": "Text shown in the app before starting a questionnaire. Enable it with the 'showIntroduction' property."
            }
          ]
        },
        "endText": {
          "allOf": [
            {
              "$ref": "#/$defs/multiLanguageText"
            },
            {
              "title": "End text",
              "description": "Text shown in the app after finishing a questionnaire."
            }
          ]
        },
        "warn": {
          "allOf": [
            {
              "$ref": "#/$defs/multiLanguageText"
            },
            {
              "title": "Warning text",
              "description": "Warning shown when the questionnaire has not been filled."
            }
          ]
        },
        "estimatedCompletionTime": {
          "type": "integer",
          "title": "Estimated completion time",
          "description": "Estimated completion time in minutes.",
          "examples": [
            1
          ]
        },
        "protocol": {
          "$ref": "#/$defs/schedule"
        }
      }
    },
    "schedule": {
      "type": "object",
      "title": "Questionnaire protocol schedule",
      "description": "Protocol including schedule for the questionnaire.",
      "required": [
        "repeatProtocol",
        "repeatQuestionnaire",
        "reminders"
      ],
      "properties": {
        "notification": {
          "$ref": "#/$defs/notification"
        },
        "repeatProtocol": {
          "allOf": [
            {
              "$ref": "#/$defs/offset"
            },
            {
              "title": "Protocol repetition",
              "description": "How frequently the protocol should be repeated for each participant.",
              "default": {
                "unit": "day",
                "amount": 7
              }
            }
          ]
        },
        "repeatQuestionnaire": {
          "allOf": [
            {
              "$ref": "#/$defs/offsetList"
            },
            {
              "title": "Questionnaire repetitions",
              "description": "What time of day questionnaires should be posed. The day that questionnaires are posed are specified with repeatProtocol, the local time is defined by this repeatQuestionnaire (units offset from repeat from midnight repeatProtocol day)."
            }
          ]
        },
        "clinicalProtocol": {
          "type": "object",
          "title": "Clinical protocol",
          "description": "Defines repetitions of the protocol after a clinical visit.",
          "required": [
            "repeatAfterClinicVisit"
          ],
          "properties": {
            "requiresInClinicCompletion": {
              "type": "boolean",
              "title": "Requires in-clinic completion.",
              "description": "Whether the test should be performed during a clinical visit."
            },
            "repeatAfterClinicVisit": {
              "allOf": [
                {
                  "$ref": "#/$defs/offsetList"
                },
                {
                  "title": "Test repetitions",
                  "description": "When to repeat the test after a clinic visit."
                }
              ]
            },
            "onDemandProtocol": {
              "type": "boolean",
              "title": "Protocol can be run on demand",
              "description": "Whether the questionnaire or task can be started by the participant on demand"
            }
          },
          "additionalProperties": false
        },
        "reminders": {
          "anyOf": [
            {
              "$ref": "#/$defs/reminderSpecification"
            },
            {
              "$ref": "#/$defs/reminderList"
            }
          ]
        },
        "completionWindow": {
          "anyOf": [
            {
              "$ref": "#/$defs/offset"
            }
          ]
        }
      }
    },
    "questionnaire": {
      "type": "object",
      "title": "Questionnaire to use",
      "description": "Reference to the questionnaire specification. This defines the questions, field type, branching logic etc.",
      "required": [
        "repository",
        "name",
        "avsc"
      ],
      "properties": {
        "repository": {
          "type": "string",
          "title": "Repository URL",
          "format": "uri",
          "default": "",
          "examples": [
            "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/master/questionnaires/"
          ]
        },
        "name": {
          "type": "string",
          "title": "Questionnaire name",
          "description": "Name should match file name under the URL provided in the repository property.",
          "default": "",
          "examples": [
            "phq8"
          ]
        },
        "avsc": {
          "type": "string",
          "title": "Schema",
          "description": "Avro Schema name as defined in RADAR-Schemas.",
          "examples": [
            "notification"
          ]
        }
      }
    },
    "reminderSpecification": {
      "type": "object",
      "title": "Reminder schedule",
      "description": "When and how often to remind participants that a questionnairie still has to be filled out.",
      "required": [
        "unit",
        "amount",
        "repeat"
      ],
      "properties": {
        "unit": {
          "$ref": "#/$defs/unit"
        },
        "amount": {
          "$ref": "#/$defs/amount"
        },
        "repeat": {
          "type": "integer",
          "title": "Repetitions",
          "description": "Number of reminders to send.",
          "default": 0
        }
      },
      "additionalProperties": false
    },
    "reminderList": {
      "type": "array",
      "title": "Reminder list",
      "description": "When and how often to remind participants that a questionnairie still has to be filled out.",
      "items": {
        "type": "object",
        "properties": {
          "offset": {
            "$ref": "#/$defs/offset"
          },
          "notification": {
            "$ref": "#/$defs/notification"
          }
        }
      }
    },
    "offset": {
      "type": "object",
      "required": [
        "unit",
        "amount"
      ],
      "properties": {
        "unit": {
          "$ref": "#/$defs/unit"
        },
        "amount": {
          "$ref": "#/$defs/amount"
        }
      }
    },
    "offsetList": {
      "type": "object",
      "required": [
        "unit",
        "unitsFromZero"
      ],
      "properties": {
        "unit": {
          "$ref": "#/$defs/unit"
        },
        "unitsFromZero": {
          "type": "array",
          "title": "Times starting at midnight",
          "description": "Times, starting from midnight, that a protocol should be suggested.",
          "items": {
            "$ref": "#/$defs/amount"
          }
        }
      }
    },
    "unit": {
      "type": "string",
      "enum": [
        "min",
        "hour",
        "day",
        "week",
        "month",
        "year"
      ],
      "title": "Amount unit",
      "description": "Duration unit attached to the amount property.",
      "examples": [
        "day"
      ]
    },
    "amount": {
      "type": "integer",
      "title": "Amount of time",
      "description": "Modified by the unit property.",
      "examples": [
        7
      ]
    },
    "version": {
      "type": "string",
      "title": "Semantic version",
      "description": "Use semantic versioning for the version.",
      "examples": [
        "0.2.3"
      ],
      "pattern": "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(-(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\\+[0-9a-zA-Z-]+(\\.[0-9a-zA-Z-]+)*)?$"
    },
    "multiLanguageText": {
      "type": "object",
      "title": "Multi-language text",
      "description": "Text in the language corresponding to property name. The property name should be a ISO 639-1 two letter language code or BCP-47 language tag.",
      "patternProperties": {
        "^[a-z][a-z](-[a-zA-Z0-9]+)*$": {
          "type": "string",
          "examples": [
            "en",
            "nl",
            "en-US"
          ]
        }
      },
      "additionalProperties": false
    },
    "notification": {
      "type": "object",
      "title": "Notification",
      "properties": {
        "title": {
          "$ref": "#/$defs/multiLanguageText"
        },
        "text": {
          "$ref": "#/$defs/multiLanguageText"
        },
        "vibrate": {
          "type": "boolean",
          "title": "Vibration on notification",
          "description": "Notification will be set to trigger vibrate on the phone"
        },
        "sound": {
          "type": "boolean",
          "title": "Sound on notification",
          "description": "Notification will be set to trigger sound on the phone"
        },
        "email": {
          "type": "object",
          "title": "Email notification",
          "description": "If email notification is enabled",
          "properties": {
            "enabled": {
              "type": "boolean"
            }
          }
        }
      }
    }
  },
  "additionalProperties": false
}

=== RADAR-base/RADAR-aRMT-protocols/RADAR-EDIFY-KCL-s1/protocol.json
{
    "version": "0.0.3",
    "schemaVersion": "0.0.1",
    "name": "RADAR EDIFY KCL s1",
    "healthIssues": ["Eating Disorder"],
    "protocols": [
      {
        "name": "PHQ8",
        "showIntroduction": true,
        "showInCalendar": true,
        "isDemo": false,
        "order": 4,
        "questionnaire": {
          "repository": "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/master/questionnaires/",
          "name": "phq8",
          "avsc": "questionnaire"
        },
        "startText": {
          "en": "This questionnaire is known as the PHQ8. Clinicians use it to assess current depression in patients.",
          "it": "",
          "nl": "",
          "da": "",
          "de": "",
          "es": ""
        },
        "endText": {
          "en": "Thank you for taking the time today.",
          "it": "",
          "nl": "",
          "da": "",
          "de": "",
          "es": ""
        },
        "warn": {
          "en": "",
          "it": "",
          "nl": "",
          "da": "",
          "de": "",
          "es": ""
        },
        "estimatedCompletionTime": 2,
        "protocol": {
          "repeatProtocol": {
            "unit": "day",
            "amount": 1
          },
          "repeatQuestionnaire": {
            "unit": "min",
            "unitsFromZero": [480]
          },
          "reminders": {
            "unit": "hour",
            "amount": 24,
            "repeat": 2
          },
          "completionWindow": {
            "unit": "day",
            "amount": 1
          },
          "notification": {
            "title": {
              "en": "Questionnaire time"
            },
            "text": {
              "en": "Please finish them within 3 days."
            }
          }
        }
      },
      {
        "name": "GAD7",
        "showIntroduction": true,
        "showInCalendar": true,
        "isDemo": false,
        "order": 3,
        "questionnaire": {
          "repository": "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/master/questionnaires/",
          "name": "gad7",
          "avsc": "questionnaire"
        },
        "startText": {
          "en": "This questionnaire is known as the GAD7. Clinicians use it to assess anxiety.",
          "it": "",
          "nl": "",
          "da": "",
          "de": "",
          "es": ""
        },
        "endText": {
          "en": "",
          "it": "",
          "nl": "",
          "da": "",
          "de": "",
          "es": ""
        },
        "warn": {
          "en": "",
          "it": "",
          "nl": "",
          "da": "",
          "de": "",
          "es": ""
        },
        "estimatedCompletionTime": 3,
        "protocol": {
          "repeatProtocol": {
            "unit": "day",
            "amount": 1
          },
          "repeatQuestionnaire": {
            "unit": "min",
            "unitsFromZero": [480]
          },
          "reminders": {
            "unit": "hour",
            "amount": 24,
            "repeat": 2
          },
          "completionWindow": {
            "unit": "day",
            "amount": 1
          },
          "notification": {
            "title": {
              "en": "Questionnaire time"
            },
            "text": {
              "en": "Please finish them within 3 days."
            }
          }
        }
      },
      {
        "name": "ED15",
        "showIntroduction": true,
        "showInCalendar": true,
        "isDemo": false,
        "order": 8,
        "questionnaire": {
          "repository": "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/master/questionnaires/",
          "name": "ed15",
          "avsc": "questionnaire"
        },
        "startText": {
          "en": "This questionnaire is known as the ED15. Clinicians use it to assess eating attitudes and behaviours over the last week.",
          "it": "",
          "nl": "",
          "da": "",
          "de": "",
          "es": ""
        },
        "endText": {
          "en": "",
          "it": "",
          "nl": "",
          "da": "",
          "de": "",
          "es": ""
        },
        "warn": {
          "en": "",
          "it": "",
          "nl": "",
          "da": "",
          "de": "",
          "es": ""
        },
        "estimatedCompletionTime": 3,
        "protocol": {
          "repeatProtocol": {
            "unit": "day",
            "amount": 1
          },
          "repeatQuestionnaire": {
            "unit": "min",
            "unitsFromZero": [480]
          },
          "reminders": {
            "unit": "hour",
            "amount": 24,
            "repeat": 2
          },
          "completionWindow": {
            "unit": "day",
            "amount": 1
          },
          "notification": {
            "title": {
              "en": "Questionnaire time"
            },
            "text": {
              "en": "Please finish them within 3 days."
            }
          }
        }
      },
      {
        "name": "SPEECH TASK",
        "showIntroduction": true,
        "showInCalendar": true,
        "isDemo": false,
        "order": 4,
        "questionnaire": {
          "repository": "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/master/questionnaires/",
          "name": "audio_story",
          "avsc": "questionnaire"
        },
        "startText": {
          "en": "",
          "it": "",
          "nl": "",
          "da": "",
          "de": "",
          "es": ""
        },
        "endText": {
          "en": "Thank you for taking the time today.",
          "it": "",
          "nl": "",
          "da": "",
          "de": "",
          "es": ""
        },
        "warn": {
          "en": "Find a quiet space.",
          "it": "Trova uno spazio tranquillo.",
          "nl": "Zoek een stille ruimte.",
          "da": "Find et roligt sted.",
          "de": "Suchen Sie sich einen ruhigen Platz.",
          "es": "Encuentra un espacio tranquilo."
        },
        "estimatedCompletionTime": 2,
        "protocol": {
          "repeatProtocol": {
            "unit": "day",
            "amount": 1
          },
          "repeatQuestionnaire": {
            "unit": "min",
            "unitsFromZero": [540]
          },
          "reminders": {
            "unit": "hour",
            "amount": 24,
            "repeat": 1
          },
          "completionWindow": {
            "unit": "day",
            "amount": 1
          },
          "notification": {
            "title": {
              "en": "Questionnaire time"
            },
            "text": {
              "en": "Please finish them within 1 day."
            }
          }
        }
      },
      {
        "name": "ESM",
        "showIntroduction": true,
        "showInCalendar": true,
        "isDemo": false,
        "order": 4,
        "questionnaire": {
          "repository": "https://raw.githubusercontent.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/master/questionnaires/",
          "name": "esm_story",
          "avsc": "questionnaire"
        },
        "startText": {
          "en": "This questionnaire is known as the ESM. Clinicians use it to assess subjective experiences in daily life.",
          "it": "",
          "nl": "",
          "da": "",
          "de": "",
          "es": ""
        },
        "endText": {
          "en": "Thank you for taking the time today.",
          "it": "",
          "nl": "",
          "da": "",
          "de": "",
          "es": ""
        },
        "warn": {
          "en": "",
          "it": "",
          "nl": "",
          "da": "",
          "de": "",
          "es": ""
        },
        "estimatedCompletionTime": 2,
        "protocol": {
          "repeatProtocol": {
            "unit": "day",
            "amount": 1
          },
          "repeatQuestionnaire": {
            "unit": "min",
            "unitsFromZero": [600]
          },
          "reminders": {
            "unit": "hour",
            "amount": 24,
            "repeat": 2
          },
          "completionWindow": {
            "unit": "day",
            "amount": 1
          },
          "notification": {
            "title": {
              "en": "Questionnaire time"
            },
            "text": {
              "en": "Please finish them within 3 days."
            }
          }
        }
      }
    ]
  }
